Repository Souvik34/Second-innings, pull requests merged in 2025-03, with the labels that each got.

#15 SOLVED issue #6
  client/src/App.jsx
  client/src/components/gallery.jsx
  client/src/components/styles/gallery.css
Labels: enhancement, apertre2.0, easy, frontend

#21 Create Security.md
  Security.md
Labels: documentation, apertre2.0

#20 Create Code of Conduct.md
  Code of Conduct.md
Labels: documentation, apertre2.0

#23 Implement Light & Dark Mode 🌞🌙
  client/package-lock.json
  client/package.json
  client/src/components/Adopt.jsx
  client/src/components/Contact.jsx
  client/src/components/Error.jsx
  client/src/components/Faq.jsx
  client/src/components/Footer.jsx
  client/src/components/Gethome.jsx
  client/src/components/Navbar.jsx
  client/src/components/Signin.jsx
  client/src/components/Signup.jsx
  client/src/components/Testimonial.jsx
  client/src/components/styles/contact.css
  client/src/context/ThemeContext.jsx
  client/src/index.css
  client/src/main.jsx
Labels: enhancement, apertre2.0, easy, frontend

#31 Navbar Updated✅
  client/src/components/styles/navbar.css
Labels: enhancement, apertre2.0, easy, frontend

#39 typography in gallery page is fixed
  client/src/App.jsx
  client/src/components/RuleandRegulation.jsx
  client/src/components/gallery.jsx
Labels: enhancement, apertre2.0, easy, frontend

#40 Improve Website Responsiveness Across All Devices
  client/src/components/Adopt.jsx
  client/src/components/Contact.jsx
  client/src/components/Domains.jsx
  client/src/components/Footer.jsx
  client/src/components/Home.jsx
  client/src/components/Navbar.jsx
  client/src/components/RuleandRegulation.jsx
  client/src/components/Signin.jsx
  client/src/components/Signup.jsx
  client/src/components/Testimonial.jsx
  client/src/components/styles/contact.css
  client/src/components/styles/domains.css
  client/src/components/styles/home.css
  client/src/components/styles/navbar.css
  client/src/components/styles/signin.css
  client/src/components/styles/testimonial.css
Labels: enhancement, apertre2.0, medium, frontend

#41 enhance and modify the parent adoption form
  client/src/components/Adopt.jsx
  client/src/components/Signup.jsx
Labels: enhancement, apertre2.0, easy, frontend

#38 screen loader issues
  client/src/App.css
  client/src/App.jsx
  package-lock.json
Labels: enhancement, apertre2.0, easy, frontend
